export const MAIN_WINDOW_ID = "mainWindowId"
export const TASK_WINDOW_ID = "taskWindowId"
export const SHARED_OBJECT = "sharedObject"
export const DOWNLOAD_INFO = "downloadInfo"
export const ROOT_PATH = "rootPath"
export const SEARCH_HISTORY = "searchHistory"
export const VIDEO_DATA = "videoData"

export const INDEX = 'index'
export const TASK_ID = "taskId"
export const AUDIO_RECEIVED = "audioReceived"
export const VIDEO_RECEIVED = "videoReceived"
export const AUDIO_TOTAL = "audioTotal"
export const VIDEO_TOTAL = "videoTotal"
export const VIDEO_PROGRESS = "videoProgress"
export const AUDIO_PROGRESS = "audioProgress"
export const TASK_STATUS = "taskStatus"
export const DOWNLOADING_STATUS = "downloadingStatus"
export const PAUSED_STATUS = "pausedStatus"
export const STOPPED_STATUS = "stoppedStatus"
export const WAITING_STATUS = "waitingStatus"
export const DELETED_STATUS = "deletedStatus"

export const NUMBER = "number"
export const TITLE = "title"
export const DESC = "desc"
export const ACCEPTS = "accepts"
export const ACCEPT_CODE = "acceptCode"
export const ACCEPT_NAME = "acceptName"
export const IS_OLD_VIDEO = "isOldVideo"
export const UP_NAME = "upName"
export const PAGE_COUNT = "pageCount"
export const VIDEO_PAGE = "page"
export const VIDEO_PAGES = "pages"
export const VIDEO_PAGE_NAME = "pageName"
export const SELECT = "select"
export const URLS = "urls"
export const VIDEO_URL = "videoUrl"
export const AUDIO_URL = "audioUrl"
export const HAS_ERROR = "hasError"
export const ERROR = "error"
export const VIDEO_PATH = "videoPath"
export const AUDIO_PATH = "audioPath"
export const OUTPUT = "output"
export const VIDEO_FINISHED = "videoFinished"
export const AUDIO_FINISHED = "audioFinished"
export const FOLDER = "folder"

export const RESUME_TASK = "resumeTask"
export const DELETE_TASK = "deleteTask"
export const PAUSE_TASK = "pauseTask"

export const ADD_TO_DOWNLOAD_LIST = "addToDownloadList"
export const START_TASK_WINDOW = "startTaskWindow"
export const UPDATE_PROGRESS = "updateProgress"
export const DOWNLOAD_FAILED = "downloadFailed"
export const DOWNLOAD_FINISHED = "downloadFinished"
export const START_MERGE = "startMerge"
export const MERGE_FINISHED = "mergeFinished"
export const MERGE_FAILED = "mergeFailed"

export const TASK_WINDOW = "taskWindow"

export const DOWNLOAD_LIST = "downloadList"
export const FINISHED_LIST = "finishedList"
export const FAILED_LIST = "failedList"
export const CHANGE_TAB = "changeTab"

export const WINDOW_CLOSING = "windowClosing"